name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild rbxfpsunlocker.sln /p:Configuration=Release

    - name: Upload compiled EXE
      uses: actions/upload-artifact@v4
      with:
        name: koronefpsunlocker-build
        path: |
          **/Release/*.exe
          **/x64/Release/*.exe
